# Random Number Generation Marathon 2025

title: Random Number Generation Marathon 2025
short_description: Generate truly random numbers—lowest KL divergence wins
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Submit your best generative models; leaderboard ranks by combined entropy and speed.
evaluation_script: evaluation_script.zip
remote_evaluation: True
start_date: 2025-07-01 00:00:00
end_date: 2030-12-31 23:59:59
published: True
tags:
  - random-number-generation
  - generative-models
  - statistics
  - benchmarking

leaderboard:
  - id: 1
    schema:
      labels: ["Entropy", "ChiSquare", "Speed", "Total"]
      default_order_by: "Total"
      metadata:
        Entropy:
          sort_ascending: False
          description: Average Shannon entropy of the generated sequence
        ChiSquare:
          sort_ascending: True
          description: χ² distance from uniform distribution
        Speed:
          sort_ascending: True
          description: Generation time per 1 M numbers (ms)
        Total:
          sort_ascending: True
          description: Weighted aggregate score

challenge_phases:
  - id: 1
    name: Development Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    challenge: 1
    is_active: True
    max_concurrent_submissions_allowed: 2
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: False
    start_date: 2025-07-01 00:00:00
    end_date: 2028-06-30 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev
    max_submissions_per_day: 3
    max_submissions_per_month: 30
    max_submissions: 100
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: code_url
        is_visible: True
      - name: hardware_used
        is_visible: True
    submission_meta_attributes:
      - name: RNG_Type
        description: Type of RNG (PRNG/TRNG)
        type: radio
        options: ["PRNG", "TRNG"]
      - name: Programming_Language
        description: Implementation language
        type: text
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".zip, .txt, .csv"

  - id: 2
    name: Test Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    challenge: 1
    is_active: True
    max_concurrent_submissions_allowed: 2
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: True
    start_date: 2028-07-01 00:00:00
    end_date: 2030-12-31 23:59:59
    test_annotation_file: annotations/test_annotations_testsplit.json
    codename: test
    max_submissions_per_day: 3
    max_submissions_per_month: 30
    max_submissions: 100
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: code_url
        is_visible: True
      - name: hardware_used
        is_visible: True
    submission_meta_attributes:
      - name: RNG_Type
        description: Type of RNG (PRNG/TRNG)
        type: radio
        options: ["PRNG", "TRNG"]
      - name: Programming_Language
        description: Implementation language
        type: text
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Dev Split
    codename: dev_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: False
    show_execution_time: True
    show_leaderboard_by_latest_submission: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: False
    show_execution_time: True
    show_leaderboard_by_latest_submission: True
